---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: recipe[pgpool2::default]
    attributes:
  - name: install
    run_list: recipe[pgpool2::install]
    attributes:
  - name: master
    run_list: recipe[pgpool2::default]
    attributes: { pgpool2: { config: { master_slave_mode: true } } }

